### ISSUE TITLE
Crash on swamp biome.

### ISSUE THREAD

**Issue by omarmartinez97** [DcZipPL/lightestlampsmod#13]
**Describe the bug**
walking,running to a certain area in my base crashes it completely, towards a swamp biome

**To Reproduce**
Not sure, I have many omega lamps placed around and below base to stop mobs from spawning

**Versions (please complete the following information):**
 - Forge: forge-32.0.88
 - Minecraft: 1.16.1
 - Mod: current release
 - Other Mods / Modpack? ATM6

**Additional context**
Error log. 
////////////////////////////////////////////
Time: 7/28/20 7:16 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot set property BooleanProperty{name=east, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{lightestlamp:light_air}
	at net.minecraft.state.StateHolder.func_206870_a(SourceFile:114) ~[?:?] {re:classloading}
	at net.minecraft.block.VineBlock.func_196544_a(VineBlock.java:228) ~[?:?] {re:classloading}
	at net.minecraft.block.VineBlock.func_225542_b_(VineBlock.java:212) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock.java:617) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:501) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:endergetic:patch_server_world,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,xf:fml:immersiveengineering:IE block update callback}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(SourceFile:390) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$17704/67048628.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:368) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:337) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:326) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:endergetic:patch_server_world,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,xf:fml:immersiveengineering:IE block update callback}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:81) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$17180/1719187758.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

**Comment by DcZipPL** [comment]
I reproduced bug and I see problem. I will update mod soon (≈24h)

**Comment by benjiben55** [comment]
i got the same problem more than one time. I link my crash log also, maybe it helps.
[crash-2020-08-02_18.50.49-server.txt](https://github.com/DcZipPL/lightestlampsmod/files/5012472/crash-2020-08-02_18.50.49-server.txt)

**Comment by DcZipPL** [comment]
Sorry that I'm not updating mod. Currently I'm sick. I will update when I feel better.

**Comment by benjiben55** [comment]
Hey, no Problem. I hope youre getting better with your Health.  😊 Mit Freundlichen Grüßen Benjamin Mruck Von: DcZipPLGesendet: Montag, 3. August 2020 22:52An: DcZipPL/lightestlampsmodCc: benjiben55; CommentBetreff: Re: [DcZipPL/lightestlampsmod] Crash (#13) Sorry that I'm not updating mod. Currently I'm sick. I will update when I feel better.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DcZipPL** [comment]
This issue is fixed. I forget to close.
